// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJHq61ygX2mWN-5xxSFT8TWtEdckUkoME',
    appId: '1:678298042878:web:44ec1a237269508a3e80af',
    messagingSenderId: '678298042878',
    projectId: 'socialapp-ae8b8',
    authDomain: 'socialapp-ae8b8.firebaseapp.com',
    storageBucket: 'socialapp-ae8b8.appspot.com',
    measurementId: 'G-WBEHL3PLCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT7B1NhPTgQwk13JUNTmdPd3LMfb6SP2I',
    appId: '1:678298042878:android:5297ceb2728a45e23e80af',
    messagingSenderId: '678298042878',
    projectId: 'socialapp-ae8b8',
    storageBucket: 'socialapp-ae8b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMKBGW8yGTL9ZPOBn5zES2r4-DwDCrFyk',
    appId: '1:678298042878:ios:eb0e285073f2fd1e3e80af',
    messagingSenderId: '678298042878',
    projectId: 'socialapp-ae8b8',
    storageBucket: 'socialapp-ae8b8.appspot.com',
    androidClientId: '678298042878-0s7r6ir25kca85d3tsi4o3260i91hns8.apps.googleusercontent.com',
    iosClientId: '678298042878-1l27976sfck7dns7l3j8c9g8alepu47i.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMKBGW8yGTL9ZPOBn5zES2r4-DwDCrFyk',
    appId: '1:678298042878:ios:347669f0358a45583e80af',
    messagingSenderId: '678298042878',
    projectId: 'socialapp-ae8b8',
    storageBucket: 'socialapp-ae8b8.appspot.com',
    androidClientId: '678298042878-0s7r6ir25kca85d3tsi4o3260i91hns8.apps.googleusercontent.com',
    iosClientId: '678298042878-fqq0t4hluer79bqecvbtlitit1rndqfv.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
